### ISSUE TITLE
Option to not remove the space before/after CSS variables

### ISSUE THREAD

**Issue by saadeghi** [parcel-bundler/parcel-css#98]
I want to minify this
```css
:root {
  font: var(--font-size) / var(--line-height) var(--font-family);
}
```
to this (see the spaces between variables)
```css
:root{font:var(--font-size) / var(--line-height) var(--font-family)}
```
but currently all spaces are being removed
```css
:root{font:var(--font-size)/var(--line-height)var(--font-family)}
```
[[example link](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%3Aroot%20%7B%5Cn%20%20font%3A%20var(--font-size)%20%2F%20var(--line-height)%20var(--font-family)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)]

**Why does it matter?**

Because there's [an issue from `postcss-values-parser`](https://github.com/postcss/postcss-custom-properties/issues/225) and the currently only workaround is to add spaces before and after the `/` which is between CSS variables.
If I minify my CSS using Parcel CSS and someone use `postcss-values-parser` on it, it will cause error.

I'm just wondering if there's a way to keep that space between variables.

**Comment by devongovett** [comment]
hmm, according to the spec, spaces are only required around the `+` and `-` operators, not `*` and `/`. See https://drafts.csswg.org/css-values/#calc-syntax:

> In addition, [whitespace](https://www.w3.org/TR/css-syntax-3/#whitespace) is required on both sides of the + and - operators. (The * and / operators can be used without white space around them.)

The postcss issue you linked to has a comment saying it is fixed:

> This should be fixed as we switched to a different value parser.

Maybe you just need to upgrade to a newer version?

**Comment by saadeghi** [comment]
You're right.  
`postcss-custom-properties` changed their parser but issue still exists in `postcss-values-parser` ([link](https://github.com/shellscape/postcss-values-parser/issues/121)) which has 5M weekly downloads and [so many dependents](https://www.npmjs.com/package/postcss-values-parser?activeTab=dependents)  
My concern is not getting that error on my own build but when I publish my package I don't want the users get the error just because of a dependency of a dependency... ([here's an example of that issue on my package](https://github.com/saadeghi/daisyui/issues/329)) and the only workaround I found was to add spaces.  

Currently I'm using `clean-css`. Since `clean-css` doesn't remove the spaces and CSSnano has [an option to remove it or not](https://cssnano.co/docs/optimisations/normalizewhitespace/), I was wondering if there's a way to make it work on Parcel CSS too.

Honestly I can't think of any other use case for it other than the workaround for the `postcss-values-parser`s issue so feel free to close this issue if it's an unnecessary feature.

**Comment by devongovett** [comment]
if you're publishing an npm package, you might not need to minify it ahead of time? you could leave it to consumers to minify? spaces are always added if the `minify` option isn't enabled.

otherwise, I'll have to think about it. maybe we can just send a pr to `postcss-values-parser` to fix it.

**Comment by romainmenke** [comment]
> Honestly I can't think of any other use case for it other than the workaround for the postcss-values-parsers issue so feel free to close this issue if it's an unnecessary feature.

We had to many issues in `postcss-preset-env` that originated from `postcss-values-parser`.
We recently migrated everything away from it and now use https://github.com/TrySound/postcss-value-parser

I would suggest not adding more workarounds for this single package.
Currently it got so bad we would need to rewrite PostCSS itself just to keep that package working :/

**Comment by romainmenke** [comment]
@saadeghi Which version of `postcss-custom-properties` are you using?
If you still have issues with it, can you open an issue here : https://github.com/csstools/postcss-plugins

**Comment by romainmenke** [comment]
> but issue still exists in postcss-values-parser (https://github.com/shellscape/postcss-values-parser/issues/121) which has 5M weekly downloads and [so many dependents](https://www.npmjs.com/package/postcss-values-parser?activeTab=dependents)

Most of the downloads in `postcss-values-parser` are because it was included in many older versions of plugins packed in `postcss-preset-env`. This number is now going down as people update to newer versions.

<img width="793" alt="Screenshot 2022-03-08 at 08 30 15" src="https://user-images.githubusercontent.com/11521496/157188116-73c3a994-7b2e-4f40-ba07-a706eca4d565.png">

The downloads of later versions are negligible :

<img width="787" alt="Screenshot 2022-03-08 at 08 31 35" src="https://user-images.githubusercontent.com/11521496/157188282-1f5d3553-786c-4b9b-b18d-1997ee452cf0.png">

**Comment by saadeghi** [comment]
Thanks for the details @romainmenke  
So I think it's better to just ignore that package.
I'm closing this. thanks everyone 🙌
